[project]
name = "dat"
version = "1.2.0"
dependencies = [
    "boto3",
    "docopt",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
dat = "dat.dat:dat"
